version: '3'

services:
  super-sicret-project:
    build: ./Image-scoring-model-for-project
    ports:
      - "8000:8000"

  ms-sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${SQL_PASSWORD}
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"

  projec-server:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - super-sicret-project
      - ms-sql-server
    command: ["/usr/bin/wait-for-it.sh", "ms-sql-server:1433", "-t", "120", "--", "dotnet", "projectServer.dll"]
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
